### ISSUE TITLE
Specmatic Not resolving $ref examples.

### ISSUE THREAD

**Issue by barath121** [specmatic/specmatic#1263]
**Description**
Specmatic Not resolving $ref examples.

**Steps to reproduce**
1. Create a api spec with example with ref as given below.
```yaml
content:
    application/json:
        schema:
            $ref: '#/components/schemas/ExampleSchema'
        examples:
            success:
                value:
                $ref: '#/components/examples/ExampleSample'
```
2. Run specmatic test this error occours.
```
[specmatic] 28-08-2024 17:06:46 debug: Test:   "Load Error FAILED"
        Reason: Error loading test data for Scenario: GET /service/application/content/v1.0/announcements -> 200
	   
    	   >> RESPONSE.BODY.$ref
	   
    	      The key $ref was found in the example success but was not in the specification
```
**Expected behavior**
Should resolve ref before validation.

**System Information:**
 - Specmatic version: Tested on Specmatic JS wrapper - 2.0.7 & 1.3.38 was working on 1.3.10.

**Comment by yogeshnikam671** [comment]
Hi @barath121, thanks for reporting this issue. 
We will look into it and get back.

**Comment by yogeshnikam671** [comment]
Hi @barath121, after spending some time on this, I found that there is a problem with the above spec. 
The ref for an example is specified as follows (without the use of `value` key) -
```yaml
content:
  application/json:
    schema:
      $ref: '#/components/schemas/ExampleSchema'
    examples:
      success:
        $ref: '#/components/examples/ExampleSample'

components:
  examples:
    ExampleSample:
      value:
        status: success
```

Try making this change and let me know if you still face any issue. Thanks again.

**Comment by yogeshnikam671** [comment]
Hi @barath121, the spec you have provided here has the "value" and "$ref" keys as siblings.
In such case, the "value" will be ignored as there can be no siblings to "$ref". Refer this [documentation](https://swagger.io/docs/specification/using-ref/) for more details.

If we go by the spec snippet you have shared, we will never see the error message that you have reported.

That said, I was able to reproduce the issue by indenting the "$ref" key such that it is the child of the value. e.g. 
```
   value:
      $ref:  SomeSchema
```
As per OpenAPI, this setup will not resolve the $ref, but will consider it as a key within some object with its value being "SomeSchema".
I am guessing you must have faced the issue that you've reported due to such a setup.
Can you please check this and get back to us?

You can also refer to this [documentation](https://swagger.io/docs/specification/adding-examples/) which explains how examples can be reused using $ref.

Looking forward to your response. Thanks.

**Comment by barath121** [comment]
Thank you @yogeshnikam671 this works.
