### ISSUE TITLE
Specmatic uses auto-generated payload over examples specified in yaml

### ISSUE THREAD

**Issue by dennisko762** [specmatic/specmatic#1301]
**Description**

As mentioned in the title while running specmatic contract tests against java spring api, instead of using the payload examples for request and response, specmatic uses auto-generated payload with random values.

**Steps to reproduce**
1. Implement a simple CRUD api in any language you prefer based on the attached yaml.
2. run following command `java -jar specmatic.jar test src/main/resources/openapi.yaml --testBaseURL=http://localhost:3000
` to test your api.
3. Observe the test payload that differes from the examples specified in the openapi.yaml file.

**Expected behavior**
Test payload equals what I specified in the examples section of the api description in the openapi.yaml file.
For the POST and GET endpoints I specified example payloads similarly as described in this article (chapter PetStore API Specification): https://specmatic.io/getting_started.html and expected my examples to be used for the test, resulting in success.

![Screenshot_1](https://github.com/user-attachments/assets/1df977dd-2fcd-48e9-86d4-7228116dc649)
![Screenshot_2](https://github.com/user-attachments/assets/c12b2c7f-8f4c-4268-bfc5-9ea6677df2b2)

**System Information:**
 - Windows 10 Professional
 - Specmatic version: 2.0.20
 - Intellij 2023.1.4
 - JDK version: 19.0.1

Thanks a lot in advance and best regards

**Comment by dennisko762** [comment]
Here is the openapi spec file (converted to json) [openapi.json](https://github.com/user-attachments/files/17006764/openapi.json)

**Comment by pranavgawri** [comment]
Hi, @dennisko762 

Thanks for reporting the problem you are facing. We will look into this and update you ASAP.

**Comment by pranavgawri** [comment]
Hi @dennisko762 ,

Apologies for getting back to you so late. The issue stems from how the examples are structured in your OpenAPI specification. For Specmatic to use your predefined examples from reference instead of generating random values, the examples need to be:

1. Defined in the `components.examples` section
2. Properly referenced in both request and response with matching names

Here's how to modify your OpenAPI spec to make it work:

```yaml
paths:
  /users:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
            examples:
              FIRST:                                    # Example name must match response
                $ref: '#/components/examples/CREATE_USER'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                FIRST:                                  # Example name must match request
                  $ref: '#/components/examples/USER_SAVED'

components:
  examples:
    CREATE_USER:
      value:
        gender: male
        name: name
        dateOfBirth: '2024-11-13'
        email: valid@mail.com
        username: username
    USER_SAVED:
      value:
        id: "123"
        gender: male
        name: name
        dateOfBirth: '2024-11-13'
        email: valid@mail.com
        username: username
  schemas:
     User:
       ...
       ...
```

Key points to note:
- Example names in request and response must match (e.g., "FIRST") for Specmatic to correlate them
- Examples should be defined under components.examples, not inside schema definitions
- Reference examples using $ref in your operations

After making these changes, Specmatic will use your predefined examples instead of generating random values during contract testing.

Please let me know if you need any further assistance. In case the problem resolved, I would request you to close the issue.

Thanks,
Pranav

**Comment by pranavgawri** [comment]
Hi @dennisko762 , 

Please find attached corrected [specification](https://github.com/user-attachments/files/17732568/spec.json).

In case the problem resolved, I would request you to close the issue

thanks,
Pranav

**Comment by samyakOO7** [comment]
Hi @dennisko762 ,

Hope you are doing fine! We are marking this issue closed, feel free to reopen it with any followup questions if needed
