### ISSUE TITLE
Unable to set Auth Token for provider contract tests

### ISSUE THREAD

**Issue by Rajaneeshkumar** [specmatic/specmatic#1454]
**Issue :** I want to set a Bearer token for my provider contract tests. When I use the SPECMATIC_OAUTH2_TOKEN key and run tests against the OpenAPI spec, Specmatic correctly picks up the value from this key. However, since my token is generated dynamically at runtime, I’m setting the SPECMATIC_OAUTH2_TOKEN value dynamically in the Node.js process during runtime. Despite this, it doesn’t seem to be working as expected

**Code block:** `const test = require('specmatic');
       it('Connections Provider Tests', async () => {
       process.env.SPECMATIC_OAUTH2_TOKEN = JWTToken;
       console.log("SPECMATIC_OAUTH2_TOKEN: "+ process.env.SPECMATIC_OAUTH2_TOKEN);
        await test('localhost', 8080, openAPIPath);
    });`
    
    
 **command** SPECMATIC_GENERATIVE_TESTS=true npm run test
    
 **Attachment**
<img width="467" alt="Screenshot 2024-11-26 at 7 54 25 PM" src="https://github.com/user-attachments/assets/126bfc77-b106-4db1-b38c-01d05067bb57">

@harikrishnan83 / @joelrosario Can you pls help me here

**Comment by samyakOO7** [comment]
Thanks @Rajaneeshkumar for reporting this issue & providing detailed information, we will investigate on it & confirm the issue shortly.

**Comment by Rajaneeshkumar** [comment]
@samyakOO7 Gentle Reminder on this !!

**Comment by pranavgawri** [comment]
HI @Rajaneeshkumar ,

Thanks for sharing the challenge you are facing. We've tested and confirm that this is a bug in how Specmatic handles dynamically set environment variables, whether through command line or runtime.
We've logged this as priority and will have a fix soon. 

I will update you on this thread once its ready.

Thanks,
Pranav

**Comment by Rajaneeshkumar** [comment]
@pranavgawri Meanwhile, Is there a workaround to pass a bearer token in the header for all tests? Thanks !!

**Comment by samyakOO7** [comment]
Hi @Rajaneeshkumar,

I’d like to share a workaround. To assign an auth token, you can refer to our documentation under the OAuth2 section: [Specmatic Authentication Documentation](https://specmatic.io/documentation/authentication.html#oauth2).

Alternatively, you can set the environment variable directly using SPECMATIC_OAUTH2_TOKEN instead of relying on Node.js’s process.env, as the latter limits the variable to the process scope.
```
SPECMATIC_OAUTH2_TOKEN=value npm test
```

Please feel free to reach out if you have any questions or need further assistance.

Thanks,
Samyak

**Comment by Rajaneeshkumar** [comment]
Hi @samyakOO7 ,

Its working fine when I pass like this `SPECMATIC_OAUTH2_TOKEN=value npm test`

As I said, my requirement is I don't have a token upfront and I generate it dynamically during run time as pre-request then need to apply the same token for all tests.

I think the same thing I have tried in the above code.

Thanks !!

**Comment by samyakOO7** [comment]
Hi @Rajaneeshkumar,

We identified an issue where process.env variables were not being correctly passed to Specmatic due to certain factors. We have resolved this issue, and the fix will be included in our next release.

Once the update is available, setting the Auth Token dynamically at runtime should work as expected.

Thank you for bringing this to our attention, looking forward for any other concerns, please feel free to inform us.

**Comment by Rajaneeshkumar** [comment]
Thanks @samyakOO7 , I have one question !! Do we have below feasibility?
**How to Validate an OpenAPI (YAML) File with Specmatic**
If there are issues, Specmatic will provide an error report highlighting:
Syntax errors
Missing required properties
Structural or semantic issues

**Comment by harikrishnan83** [comment]
> Thanks @samyakOO7 , I have one question !! Do we have below feasibility? **How to Validate an OpenAPI (YAML) File with Specmatic** If there are issues, Specmatic will provide an error report highlighting: Syntax errors Missing required properties Structural or semantic issues

hello @Rajaneeshkumar , since this is a separate topic, request you start a fresh [discussion](https://github.com/znsio/specmatic/discussions) on this. Thanks.

**Comment by harikrishnan83** [comment]
hello @Rajaneeshkumar , the fix for this issue is available in [specmatic-node release 2.0.43](https://github.com/znsio/specmatic-node/releases/tag/2.0.43). Marking this as closed. Please feel free to re-open if you have any questions on this. Thanks.
