### ISSUE TITLE
Contracts being failing  on higher springboot

### ISSUE THREAD

**Issue by subhadrasaraf** [specmatic/specmatic#1488]
we are facing issues of specmatic contracts being failing  on higher springboot
attached are the screeshots

![image (9)](https://github.com/user-attachments/assets/d492afd5-4ae3-4ff7-911b-26cfe0162c20)
![image (10)](https://github.com/user-attachments/assets/72235a91-cce6-4964-b488-7d591c61d7fb)
![image (11)](https://github.com/user-attachments/assets/c4b444cc-2a05-4541-8c2c-8eff7fe8e05a)

![image (8)](https://github.com/user-attachments/assets/e958a2e5-c32d-4963-9a08-e7088d09ba69)

![image (7)](https://github.com/user-attachments/assets/c3f21e86-e3ac-4c0d-99b8-803bf4f0aaec)

**Comment by harikrishnan83** [comment]
hello @subhadrasaraf , thanks for reporting this. We will take a look and get back.

**Comment by subhadrasaraf** [comment]
@harikrishnan83 , can you please update on this

**Comment by harikrishnan83** [comment]
hello @subhadrasaraf , here is one of our [sample projects](https://github.com/znsio/specmatic-order-api-java/blob/main/pom.xml) which is using Springboot 3.4 which is the latest stable version and it is working. Can you please share the beginning of the stacktrace of the error you are seeing so that we can see the error being reported? Thanks.

UPDATE: Also noticed you are Specmatic version 1.3.10 (that is quite old), can you please use latest version (2.0.49)?

**Comment by harikrishnan83** [comment]
hello @subhadrasaraf , as discussed, the issue was indeed related to Specmatic version 1.x being used. After upgrading to latest version of Specmatic, we are not seeing this issue anymore. Closing this issue for now. Please feel free to re-open if you have any questions on this. Thanks.
