### ISSUE TITLE
Specmatic runs the entire spec file multiple times when re-using the response from one api in multiple spec files

### ISSUE THREAD

**Issue by aanchal-narang** [specmatic/specmatic#269]
**Description**
Specmatic is running the entire spec file everytime we are re-using the response in subsequent spec files to hit any other dependent api . The base api is included in "baseurls" object in specmatic.json file.

**Steps to reproduce**
1. Create a loginApi.spec file that includes a login api test
2. Include the path for this loginApi.spec in "environments"  : "local": "baseurls" object in specmatic.json file.
3. Export the login token from loginApi.spec file and re-use it in other spec files while hitting an api.

**Expected behavior**
**The token should be generated once and same should be re-used in subsequent specmatic files.**

**Actual behaviour**
New token is being generated everytime while running the dependent spec files.

**Comment by jaydeepk** [comment]
Thanks for reaching out to us @aanchal-narang.
Apologies for the delayed response.
We'll have a look at this and get back to you.

**Comment by harikrishnan83** [comment]
@aanchal-narang We have documented our view on the recommended approach for handling authentication and authorization while running contract tests here.
[https://specmatic.in/documentation/authentication.html](https://specmatic.in/documentation/authentication.html)

In short we would prefer that the auth be disabled at this stage of testing because that is a concern that could be addressed at higher level test like workflow test, end to end, etc.

Closing the issue for now. Please feel free to re-open if you have any questions on this.
