### ISSUE TITLE
Need @ignore/@exclude tag provision for spec files 

### ISSUE THREAD

**Issue by nidhi-tomar93** [specmatic/specmatic#273]
**Is your feature request related to a problem? Please describe.**
@ignore/@exclude tags should be provided to ignore the set of scenarios in Specmatic.

**Describe the solution you'd like**
@ignore/@exclude tags should be supported to ignore the scenarios in the spec file.

**Comment by vikram-rao** [comment]
Hi @nidhi-tomar93, can you let us know why you would like this feature? How will this be useful to you?

**Comment by jaydeepk** [comment]
We have since moved away from the Gherkin based syntax to industry standard API specifications like OpenAPI, AsyncAPI, etc. which we now treat as API contracts. Please do watch our latest [conference videos](https://www.youtube.com/watch?v=3HPgpvd8MGg&list=PL9Z-JgiTsOYRERcsy9o3y6nsi5yK3IB_w) for more details. Closing this issue for now, please feel free to reopen if required.
