### ISSUE TITLE
Not able to export the value of an object from a response-body array

### ISSUE THREAD

**Issue by Vinstan-gif** [specmatic/specmatic#312]
**Description**
Not able to the access the exported value from another spec file when i am trying to export the value of an object from a response-body which is having data-type as array.

**Steps to reproduce**
1. Create a Spec file and add `And export objectValue = response-body.array[0].object` in tryStub.spec after response body and add the path in specmatic.json file.
2. Create another Spec(try2Stub) file to import the response and add this file in the specmatic.json file.	
3. Run this script: specmatic test --host=localhost --port=5000 --env=local.

**Expected behavior**
response-body.Array[0].object should return value of the object.

**Screenshots**
In the screenshot i am exporting the response.
![Screenshot from 2021-08-20 18-57-00](https://user-images.githubusercontent.com/62533251/130240404-8e43ec0d-b537-4e3a-bddf-10b7b5da3a41.png)

In the screenshot i am import the response.
![Screenshot from 2021-08-20 18-51-07](https://user-images.githubusercontent.com/62533251/130240548-6f38a6a3-6ad7-4111-bbec-3297f255f4d2.png)

Added the files in baseUrl and in specmatic.json
![Screenshot from 2021-08-20 18-52-11](https://user-images.githubusercontent.com/62533251/130240672-2d145514-23f5-4b26-a52f-6a216bd425b0.png)

Error on running the 2 files.
![Screenshot from 2021-08-20 18-55-35](https://user-images.githubusercontent.com/62533251/130240831-bf99b197-69f5-4a6c-8f2e-8902e9f09d04.png)

**System Information:**
 - OS & version: [ubuntu 20.04]
 - Browser & version: [chrome - Version 92.0.4515.131 (Official Build) (64-bit)]
 - Specmatic version: [0.28.5]
 - JDK version: [11.0.11]

**Comment by jaydeepk** [comment]
Thanks for reaching out @Vinstan-gif .
Apologies for the delayed response.
We'll have a look at this, but also want to check if you are still facing this issue

**Comment by harikrishnan83** [comment]
@Vinstan-gif apologies for the long radio silence on this. We have since

The capability you are using (`export`) was built for Authentication where we wanted to use the token from a auth response in making API calls.

We have since moved from Gherkin based DSL to OpenAPI specification which has inbuilt support security schemes. Here is a detailed overview about how we handle authentication and authorisation for OpenAPI.

[https://specmatic.in/documentation/authentication.html](https://specmatic.in/documentation/authentication.html)

Closing for now. Please feel free to reopen if you have any more related questions.
