### ISSUE TITLE
Cannot import value inside an array in examples

### ISSUE THREAD

**Issue by Vinstan-gif** [specmatic/specmatic#326]
**Description**
Not able to import a value in an array which is in the examples.

**Steps to reproduce**
1. Create .spec file and export any value. eg:(trail.spec)
2. Create another .spec file and import the value from trail.spec in an array which is in the examples.

**Expected behavior**
Should be able to read the imported value which is in the array.

**Screenshots**
File from which the value is exported:
![Screenshot from 2021-09-14 18-41-53](https://user-images.githubusercontent.com/62533251/133265568-9ea71cd2-0bef-4388-8afe-a9f6d5930fd6.png)

File in which the value is imported:
![Screenshot from 2021-09-14 18-42-02](https://user-images.githubusercontent.com/62533251/133265774-089724a8-79ed-4ffb-8d17-f8bae9712b46.png)

Error got on running:
![Screenshot from 2021-09-14 19-02-23](https://user-images.githubusercontent.com/62533251/133266925-50fa5102-69f0-4092-a5b3-f19fb9eed8fc.png)

**System Information:**
 - OS & version: [Ubuntu 20.04]
 - Browser & version: [Version 93.0.4577.82 (Official Build) (64-bit)]
 - Specmatic version: [0.28.5]
 - JDK version: [11.0.11]

**Comment by jaydeepk** [comment]
Thanks for reaching out to us @Vinstan-gif 
Apologies for the delayed response.
Are you are still facing this issue ?
Please do let us know

**Comment by harikrishnan83** [comment]
@Vinstan-gif reviving this thread from a long time ago. We have since moved away from the Gherkin based syntax to industry standard API specifications like OpenAPI, AsyncAPI, etc. which we now treat as API contracts. Please do watch our latest [conference videos](https://www.youtube.com/watch?v=3HPgpvd8MGg&list=PL9Z-JgiTsOYRERcsy9o3y6nsi5yK3IB_w) for more details. Closing this issue for now.
