### ISSUE TITLE
Use examples object from open-api spec

### ISSUE THREAD

**Issue by bobjana** [specmatic/specmatic#648]
Generating responses from api-spec [Example-Objects](https://swagger.io/specification/v3/#example-object) would be a great feature that fits well with the projects philosophy of being contract driven. This project demonstrates the feature [microcks](https://microcks.io/documentation/guides/openapi-101/#2-basic-operation-in-openapi) whereby request examples are also mapped to request responses.

I would imagine the order of matching requests could be:
* static mapping under data directory
* example objects in api-spec
* default to randomly generated responses

**Comment by jaydeepk** [comment]
Thanks for reaching out to us @bobjana.
We do support examples in specs.
Could you please elaborate a bit on what you exactly mean by 'generating responses from example objects' ?

**Comment by aeoncl** [comment]
Hello guys, sorry to bring back this issue from the dead but we ran into a similar usecase, that would be cool if the requests & responses examples from the OpenAPI spec could be used as stubs !

I think Specmatic ignores the responses examples currently:

- When Testing, we only match on the ResponsePattern but the content doesn't matter, if i have a response example with a concrete value, Specmatic checks if the response matches the Pattern but if it's not the same exact value, the test will not fail.

- When Stubbing, i don't think stubs are being created from the examples at all currently

So yeah, being able to just fire up a stub from the OpenAPI examples (both requests & response) would be very valuable because, examples baked-in the openAPI are basically provider approved mocks !)

**Comment by harikrishnan83** [comment]
@aeoncl Thanks for bumping this up. We will get back to you on this shortly.

**Comment by joelrosario** [comment]
Hi @aeoncl, @bobjana, sorry for the radio silence.

> Hello guys, sorry to bring back this issue from the dead but we ran into a similar usecase, that would be cool if the requests & responses examples from the OpenAPI spec could be used as stubs !
> 
> I think Specmatic ignores the responses examples currently:
> 
> * When Testing, we only match on the ResponsePattern but the content doesn't matter, if i have a response example with a concrete value, Specmatic checks if the response matches the Pattern but if it's not the same exact value, the test will not fail.

@aeoncl your observation about how Specmatic validates the response in contract tests is correct.

> * When Stubbing, i don't think stubs are being created from the examples at all currently
> 
> So yeah, being able to just fire up a stub from the OpenAPI examples (both requests & response) would be very valuable because, examples baked-in the openAPI are basically provider approved mocks !)

Specmatic can use examples in the specification as expectations for service virtualisation / stubbing. Here's the [documentation](https://specmatic.in/documentation/service_virtualization_tutorial.html#examples-as-expectations) that describes how it works.

Closing for now, but please reply and reopen if you have further questions.
