### ISSUE TITLE
docs: comparision with pact should consider pact-metrics capability

### ISSUE THREAD

**Issue by kiranpatel11** [specmatic/specmatic#684]
**Description**
In documentation, for comparision with other tools like Pact and PactFlow, can you also consider the `PactMatrics` and `can-i-deploy` capabiliies ?

These capabiliies are useful in CI automation and fill the gap of integration issues that may arise due to the difference in timeline of consumer and provider versions getting promoted though different environments during the lifecycle.

**Proposal**
To leverage the existing pact-broker capability, specmatic should probably support generating the pactfile from Specmatic DSL/OAS, assuming specmatic DSL supports matches for smart assertions.

**Comment by jaydeepk** [comment]
Thanks a lot for reaching out with this proposal.
We'll have a look at this, evaluate, and get back to you.

**Comment by harikrishnan83** [comment]
@kiranpatel11 Pact integration is not part of our current roadmap. About comparison related questions can you raise a separate issue please?

**Comment by kiranpatel11** [comment]
@harikrishnan83, a question-

Without such integration with any tool like pact-matrix, how the specmatic would help in below scenarios-

1. Consumer completes functional tests using the OAS as stubs for an incremental change.
2. Specmatic runs contract tests using the OAS against the provider implementation....and it FAILS.
3. How would you stop consumer from deploying this incompatible change ?

Without such integration, I think it does not close the loop and is not that useful in the real-world scenarios.

**Comment by harikrishnan83** [comment]
@kiranpatel11 I encourage you to watch our conference videos about contract driven development to understand the overall approach better. Hope that will answer many of your questions here.
[Agile India](https://youtu.be/uaaevRw0TN4)
[API Specifications Conference - San Francisco](https://youtu.be/U5Agz-mvYIU)

Also please do re-open issues if you have additional questions so that we can monitor them actively. Otherwise please do [contact us](https://specmatic.in/contact-us/) on our website for clarifications.
