### ISSUE TITLE
Issue with Handling Range (4XX) in Response Status Codes

### ISSUE THREAD

**Issue by premnaththirumalaisamy** [specmatic/specmatic#696]
**Description**
When attempting to use ranges like 1XX, 2XX, etc., in the response status codes, the contract fails to load with the following error message: Could not load /Users/path_to_contract/Contract.yaml: For input string: "4XX"

**Steps to reproduce**
Contract file

> openapi: 3.0.1
info:
  title: Sample API
  version: 1.0.0
paths:
  /sample-endpoint:
    get:
      summary: Get Sample Data
      description: Retrieve sample data from the API.
      responses:
        '4XX':
          description: Client Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: An error occurred on the client side.

**Expected behavior**
specmatic stub or specmatic test works fine with such open API(3.0.1) specification

**Additional context**
stacktrace shows _java.lang.NumberFormatException: For input string: "4XX"._ 

**OpenApiSpecification.kt** 

> status = if (status == "default") 1000 else status.toInt()

The code is assuming that the response status code will be either "default" or an integer value and breaks when range ("4XX") is passed.

**Comment by harikrishnan83** [comment]
@premnaththirumalaisamy Thanks for reporting the issue.

I agree that Specmatic should not be throwing ```NumberFormatException ``` in this case. We will look into it.

However from an API design point of view having a generic ```4xx``` may not convey the API behaviour with sufficient clarity to the API consumers. We generally recommend going with specific error codes because that way you can qualify each response better. If the intent here is to reduce duplication of error response schema, that could be solved by extracting it to component/schemas section and referenced. Please let me know if I am missing something.

Also, as you may have seen in some of our [examples](https://github.com/znsio/specmatic-order-contracts/blob/09d4d6944e7b23152554da9211f66b11f5edcde0/in/specmatic/examples/store/api-order-expanded-v1.yaml#L74), Specmatic can correlate the examples across request and responses to generate tests. Having a non-specific error code such as ```4xx``` means it is not possible to map various input possibilities with the specific error outcomes such as 422, 404, etc.

**Comment by premnaththirumalaisamy** [comment]
Thank you for your response. I completely understand and agree to your point about using specific error codes for better clarity in API behavior. However, in this particular situation, I'm working with an existing codebase where making modifications to the API design is not feasible due to various constraints.

Also any specific reason as to why **.yml** file extension is not supported ? All the contracts in the current codebase are defined with type **yml**.

**Comment by harikrishnan83** [comment]
@premnaththirumalaisamy Thanks for sharing your context. Just a suggestion, changing the response codes to more specific version may not entail API design change. Please do correct me if I am wrong.

However, we will take a look how we can handle the non-specific error codes such as '4xx' better.

About ```.yml``` file, no specific reason. This is a good catch and quite an easy fix too. Can you please log a separate issue for this?

**Comment by premnaththirumalaisamy** [comment]
https://github.com/znsio/specmatic/issues/697

**Comment by harikrishnan83** [comment]
Thanks @premnaththirumalaisamy

**Comment by harikrishnan83** [comment]
@premnaththirumalaisamy this is an important item. I am re-opening the same. Below is our proposed fix.
* When we encounter non specific error codes such as "2xx", "4xx", etc. we throw a warning about the same (instead of the NumberFormatException that we currently see)
* And this non-specific response will not be taking in to consideration for the purpose testing, stubbing, etc.

We can always iterate on this and see if the solution can improved upon.

cc @jaydeepk

**Comment by joelrosario** [comment]
Hi @premnaththirumalaisamy, we've updated Specmatic to show a more meaningful error when a non numerical (such as 2xx, 4xx, etc) is seen in the specification. Hope this helps.

Please feel free to reopen this if you have any followup questions.
