### ISSUE TITLE
External test case filters out unrelated spec scenarios

### ISSUE THREAD

**Issue by matus-m** [specmatic/specmatic#711]
**Description**
External spec filters out unrelated scenarios parsed from API schema

**Steps to reproduce**
Create a schema with multiple `GET` endpoints that return 200 response e.g. 
Create a spec file with single scenario for 1 of the endpoints of the schema, that asserts a returned status using `Then status 200`.   
When the test runs, all scenarios from the API schema that have the same response code will be ignored and no test case will be generated for them (with the exception of the one that I actually describe in the gherkin spec).
This is most probably due to filtering in: https://github.com/znsio/specmatic/blob/b66b03c9e360f0a7f38668f6ed03011af97ea1b5/core/src/main/kotlin/in/specmatic/core/Feature.kt#L1657-L1661
where **all** `scenarioInfosBelongingToIncludedSpecifications`  are filtered even if there is no scenario in my spec that actually describes that endpoint. 

**Expected behavior**
The logic should not filter out unrelated endpoints - only the one with matching request pattern.

**Comment by jaydeepk** [comment]
Thanks a lot for reaching out to us @yntelectual.
We'll have a look at this and get back to you.

**Comment by jaydeepk** [comment]
@yntelectual, could you please elaborate a bit when you say:
`The logic should not filter out unrelated endpoints`
By ```unrelated endpoints``` , do you mean endpoints which are defined in open api soec, but are not present in the gherkin spec?

Just to provide a bit of background regarding the usage of gherkin specs:
We have provided support for gherkin specs mainly as a means to externalise examples/test cases.
This could be useful in situations where let's say you have an open api spec with no examples in it.
And maybe due to permissioning/access issues (or any other reason for that matter), you can't update the open api spec with the examples.
In such cases, you can reference the open api specification in a gherkin spec and define
examples there. The gherkin spec then becomes the primary document that is leveraged by Specmatic to run tests.

Hence, when we use a gherkin spec, Specnatic will only run tests based on the scenarios defined in the spec.
Specmatic ignores the endpoints in the open api specification as they may not have examples associated with them and the user has made an explicit choice to create a gherkin spec with examples.

For more details, please refer to the [documentation](https://specmatic.in/documentation/contract_tests.html#externalising-examples--test-cases)

It would be helpful if you could share examples of your open api spec and gherkin spec so that we could better understand your usecase and will also help us solve your issue.

**Comment by matus-m** [comment]
hi @jaydeepk thanks for clarification - but its does not seem to match the behaviour I get. 
As you can see in the test case I added - if you have an API schema that will result in 10 scenarios, and then you create an external gherkin spec with just a single scenario, only for one of the endpoints, then what you get is(see the above snippet of `Feature.kt`:

list of Gherkin scenarios **plus** list of scenarios from schema **excluding** those schema scenarios that have the same response status. 

So its neither a full merge, nor is it `only run tests based on the scenarios defined in the spec.` as you mentioned. 
If my schema contains:
```
GET /orders/ -> 200 return list of all orders
POST /orders/ -> 201 new order created
GET /users/ -> 200 return list of all users
POST /users/ -> 201 new user created
```
and i define a spec with 
```
When GET /orders
Then Status 200
```
Specmatic will execute 3 tests - excluding the `GET /users/ -> 200 return list of all users` because it matches the response status of my spec scenario. 

Maybe this behaviour could be controlled by a flag - whether only scenarios defined in gherkin spec should be run or a combination of both.

**Comment by jaydeepk** [comment]
@yntelectual , Thanks a lot for your elaborate response and your PR.
You are right about Specmatic neither doing a full merge, nor just only relying on the gherkin spec to generate tests.
This definitely looks like a bug , we'll review it and get back to you.

**Comment by joelrosario** [comment]
@yntelectual thanks for the PR fixing this! I've merged it.

A release with the fix will be out soon.
