### ISSUE TITLE
Content expected while is not defined in the contract

### ISSUE THREAD

**Issue by fradaloisio** [specmatic/specmatic#749]
**Description**
Contect expected while no response content is defined in the contract.

**Steps to reproduce**
1. Create the `definition.yaml` and the `patch_10.yaml ` files with the content of this gist https://gist.github.com/fradaloisio/9df221d7dfad972f5120bb19fc3ef8b8
2. create a folder test_data and move the patch_10.yaml file there
3. run the command `java -jar specmatic.jar stub --strict --data=test_data definition.yaml`

**Expected behavior**
Since there is no responses.content defined in the definition.yaml, I expect that the stub is not expecting a content.

**Screenshots**
![Screenshot 2023-09-26 at 18 04 40](https://github.com/znsio/specmatic/assets/3777557/38764a8a-85b3-44d0-be58-f0090c738486)

**System Information:**
 - OS & version: MacOS 13.5.2
 - Specmatic version: 0.74.0
 - JDK version: OpenJDK Runtime Environment Homebrew (build 11.0.20.1+0)

**Comment by joelrosario** [comment]
Hi @fradaloisio,

1. The expectation file name should end with `.json` (so `patch_10.json` here). Any file that does not end with `.json` in `definition_yaml` will be ignored by Specmatic.
2. `value` is null in `patch_10.json`, but it is not nullable according to the specification, which is what Specmatic reports in the error in your screenshot. I have tested locally with the files at the gist that you shared and got the same error.
3. I also updated `patch_10.json` to match the specification, and Specmatic accepted it, and in fact returned an empty response when I sent it the expected request.

Can you check again if the error still exists after updating the expectation file (`patch_10.yaml`) or specification (`definitions.yaml`) so that the two match.

**Comment by fradaloisio** [comment]
Hi @joelrosario, you are right ... I've added `value: {}` and it worked.
Thanks for spotting this.

**Comment by joelrosario** [comment]
Great, glad to have been of help! Closing this issue.
